# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaiSiBuDeJie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaiSiBuDeJie



pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.8.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD', '~> 2.0.3'

  target 'BaiSiBuDeJieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaiSiBuDeJieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
